name: aln
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bwa-mem2=2.2.1
  - bwakit=0.7.17.dev1  
  - samtools=1.16.1
  - elprep=5.1.3
  - mosdepth=0.3.3
  - qualimap=2.2.2a
  - fastqc=0.12.1
  - multiqc=1.14
  - htslib=1.6